FROM node:18-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY server/package*.json ./
RUN npm install --production

# Копируем весь код сервера
COPY server/ .

EXPOSE 3000

CMD ["node", "index.js"]